# Generated by Django 5.2 on 2025-06-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='')),
                ('product_invoice', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=250)),
                ('product_description', models.CharField(max_length=500)),
                ('product_brand', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_offer_price', models.IntegerField(blank=True, null=True)),
                ('product_size', models.CharField(max_length=50)),
                ('product_offer', models.IntegerField(blank=True, null=True)),
                ('product_mfg', models.DateField()),
                ('product_expairy', models.DateField()),
                ('product_category', models.CharField(choices=[('Fresh_Products', 'Fresh Products'), ('Dairy_Eggs', 'Dairy Eggs'), ('Meat_Seafood', 'Meat Seafood'), ('Pantry', 'Pantry'), ('Frozen_Products', 'Frozen Products'), ('Snacks_Bakery', 'Snacks Bakery'), ('Drinks', 'Drinks'), ('Homeware', 'Homeware')], max_length=50)),
            ],
        ),
    ]
