# Generated by Django 5.2 on 2025-06-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_product',
            name='product_expairy',
        ),
        migrations.RemoveField(
            model_name='add_product',
            name='product_mfg',
        ),
    ]
