# Generated by Django 5.2 on 2025-06-23 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_shipping_address_user'),
        ('veva', '0004_rename_register_user_user_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veva.user_register'),
        ),
    ]
