# Generated by Django 5.2 on 2025-06-24 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_remove_add_product_product_expairy_and_more'),
        ('user_app', '0005_alter_shipping_address_user'),
        ('veva', '0004_rename_register_user_user_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.add_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veva.user_register')),
            ],
        ),
    ]
