# Generated by Django 5.2 on 2025-05-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veva', '0003_register_user_delete_user_registers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register_user',
            new_name='user_register',
        ),
    ]
