# Generated by Django 5.2 on 2025-07-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veva', '0004_rename_register_user_user_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='send_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
